name: Lint C/C++ Code

on: [push, pull_request, workflow_dispatch]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cpplint
        run: pip install cpplint

      - name: Run cpplint
        run: find . -name *.hpp -o -name *.cpp -type f | xargs cpplint
